// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD305BcsOqm81pKTwv3bIfmuZEg-DKCaGE',
    appId: '1:560599498850:android:2a9a57fd123149719fd13b',
    messagingSenderId: '560599498850',
    projectId: 'movie-night-4279a',
    databaseURL: 'https://movie-night-4279a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'movie-night-4279a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEy3U3qFFEhyPir_3qArLX1cZWgBYvN3E',
    appId: '1:560599498850:ios:a35f52d4628bf8039fd13b',
    messagingSenderId: '560599498850',
    projectId: 'movie-night-4279a',
    databaseURL: 'https://movie-night-4279a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'movie-night-4279a.appspot.com',
    androidClientId: '560599498850-0ujq5hemo7gd2rh5n1e14a8t5qbo4b1j.apps.googleusercontent.com',
    iosClientId: '560599498850-5ci5gug2ov33rrln1b0u5au3b8ppales.apps.googleusercontent.com',
    iosBundleId: 'eg.edu.miuegypt.csc422.movienight',
  );
}
